language: node_js

node_js:
  - lts/*

branches:
  only:
    - hexo

cache:
  directories:
    - node_modules

install:
  - npm install -g hexo-cli
  - npm install
  - wget http://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64
  - chmod 755 ossutil64

os:
  - linux

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: hexo
  fqdn: www.leelib.com
  local_dir: public
  target_branch: master

after_deploy:
  - ./ossutil64 rm oss://kaij/ -r -f -e $OSS_ENDPOINT -i $OSS_ACCESSKEYID -k $OSS_ACCESSKEYSECRET

