baseURL: https://www.leelib.com/
languageCode: zh-CN
title: 逃避虽然可耻但有用
theme: fika
metaDataFormat: yaml
paginatePath: page
uglyURLs: true
hasCJKLanguage: true

permalinks:
  posts: /:year/:month/:day/:filename
  /: /index.html


outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom

author:
  name: leaker


params:
  sub_title: 少壮不努力，一生在内地
  logo: /img/logo.webp
  cn_icp_id:  # China Website Internet Content Provider ID. If site not deploy in china, keep empty

menu:
  main:
    - name: home
      title: 主页
      url: /
      identifier: home
      weight: 1
    - name: archives
      title: 归档
      url: /archives/index.html
      identifier: archives
      weight: 2
    - name: about
      title: 关于
      url: /about/index.html
      identifier: about
      weight: 3
    - name: disappear
      title: 消失
      url: /disappear/index.html
      identifier: disappear
      weight: 4

markup:
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
